generatorName: typescript-fetch
# https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/typescript-fetch.md
additionalProperties:
  npmName: "@hra-api/ts-client"
  npmVersion: 0.12.1
  supportsES6: true
  useSingleRequestParameter: true
  importFileExtension: .js
