generatorName: typescript-fetch
gitUserId: x-atlas-consortia
gitRepoId: hra-api
# https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/typescript-fetch.md
additionalProperties:
  npmName: '@hra-api/ts-client'
  npmVersion: 0.16.1
  licenseName: MIT
  supportsES6: true
  useSingleRequestParameter: true
  importFileExtension: .js
